### ISSUE TITLE
Changes/Updates to Data Model

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-cms#141]
@evz @jeancochrane 

I tried to lay out the additions we've made to the data model in the bigger concepts and then into specifics with each overall concept (like Organization memberships) that we've added/modified with the column and name of column in our updated sheet (we haven't shared a copy yet as we are currently working on the data, let me know if some demonstration data would be helpful)

# Big concepts

**Organizations**
1) Having the ability to capture exact end dates for different characteristics. For instance the parent relationship can now have an exact end date - whereas before we only had "do not assume to current date" as an option.
2) We've introduced a concept of an Organization being created or disbanded. This would mean none of it's other characteristics (Parent, Site, AOO, Membership) should exist before it's date of creation or after it's date of disbandment.  As part of this an Organization can have dates of first/last citation where we don't have a clear date of creation or date of disbandment. (Sticky point here, in theory organizations could be disbanded and then "re-activated" at some later point - haven't come across this yet in our data, but I know that can happen, particularly for military formations).

**Events/Incidents**
1) We've introduced the concept that Events (we're starting to call them Incidents based user feedback) can have updates and a status classification - like when charges are brought against suspected perpetrators. There are a LOT of questions to still resolve for this - but I wanted to flag it rather than having to go back and build it in later.

## Change with dates
We added separate columns for Month, Day and Year after every date field in the column to help clarify things as we work across different date formats - 

# Organizations

## Organization Creation/Disbandment (new concept)

- Organization:date_first_cited
- Source: Organization date_first_cited
- Confidence: Organization date_first_cited
- start date of Organization? Y/N - "Y" would make this the date of creation, "N" would make it date first cited
- Organization:date_last_cited
- Source: Organization date_last_cited
- Confidence: Organization date_last_cited
- Organization:open_ended? Y/N/E - "Y" = we assume this org continues to exist , "N" = we do not assume that this org continues to exist but we don't have an exact end date, and "E" = the Organization:date_last_cited is the date of disbandment for this org, it's Site, Parent/Child, AOO and Memberships should not exist after this date.

## Parent relationships

- Start date of OrganizationOrganization Y/N? (we've added the ability to say if the OrganizationOrganization:date_first_cited is the start date or date first cited)
- OrganizationOrganization:open_ended - we've added "E" = the parent relationship ended on OrganizationOrganization:date_last_cited, "Y" (we assume this parent relationship continues to exist) and "N" (we do not assume this parent relationship continues to exist, but don't have an exact end date)

## Organization Site

- Site: Exact Location - Longitude or OSM Name
- Site: Exact Location - Latitude or OSM ID - I see these as additional fields on top of the existing Site data. In my thinking exact locations are either long/lat given in a source, or they are an OSM Name/ID that needs the additional context of the other Site fields (like the city and state/governorate/etc) for it to be meaningful for users. For example - http://www.openstreetmap.org/way/240207676 - is a low confidence exact location for an organization, but it's OSM Name "Zona Militar" doesn't tell users much.
- OrganizationSite:open_ended (Y/N/E) - "E" = the OrganizationSite:date_last_cited is the exact end date for this Organization's Site, "Y" = we assume this Organization continues to be based at this Site, and "N" = we do not assume this Organization continues to be based at this Site, but we do not have an exact end date

## Area of Operations

- start date of area of operation? Y/N - added ability to flag if Date of first citation for area of operations is the start date
- Assume Area of Operations to Current Date? (Y/N/E) - "E" = the Date of last citation for area of operations is the exact end date for this Organization operating in this area, "Y" = we assume this Organization continues to operate in this area to the current date, "N" = we do not assume this Organization operates in this area to the current date, but we do not have an exact end date

## Organization Membership

- start date of OrganizationMembership? Y/N - added column to flag if Date of first citation for OrganizationMembership:member_id is start date for membership
- end date of OrganizationMembership? Y/N - added column to flag if end date of OrganizationMembership? Y/N is end date for membership

# Events/Incidents

- Date of publication - created separate column to capture when the allegation was first published - we are doing this to help capture when was the first date that government should have known about the alleged abuse(s)
- date of last update - if there is an update in the alleged incident (for instance government has still not prosecuted someone, or conversely a judgement is reached in a trial) - we still have some thinking to do on this concept. Wanted to add the concept rather than forcing you to backtrack.
- Status as of last update - we'd need to create or adopt some typology to classify the status (for instance if a trial is ongoing) - still lots of thinking for us to do here - but wanted to add the concept rather than forcing you to backtrack.
- Site: Exact Location - Longitude or OSM Node Name
- Site: Exact Location - Latitude or OSM Node ID

# Would be Nice
1) Headquarters can have multiple names - right now we capture that on separate rows or create a "canonical" name - would be nice to have ability to capture the aliases of a HQ in some way. HQ's are buildings/bases and not "Organizations" in our thinking so we can't capture aliases by making an HQ an Organization.
2) There are a number of additional data points for People that we don't yet capture (gender, birth/death dates, etc.) - we're not sure what/whether we'll be capturing these additional characteristics - but I wanted to flag this in case it is something that would be very difficult to implement later.

# Tasks

## General

- [x] Check for existing "open ended" attributes and migrate them to new enumerated type

## Organizations

- [X] Organization:date_first_cited (sourced and confidence)
- [X] Organization:real_start
- [X] Organization:date_last_cited (sourced and confidence)
- [X] Organization:open_ended?
- [ ] Data validation: If "E" = the Organization:date_last_cited is the date of disbandment for this org, it's Site, Parent/Child, AOO and Memberships should not exist after this date.
- [x] Update forms
- [x] Update templates

## Compositions

- [x] Composition:startdate
- [x] Composition:open_ended (same as orgs above)
- [x] Data validation
- [x] Update forms
- [x] Update templates

## Emplacement

- [x] Emplacement:Exact Location
- [x] Emplacement:open_ended
- [x] Emplacement:aliases
- [ ] Data validation
- [x] Update form
- [x] Update templates

## Association

- [x] Association:realstart
- [x] Association:open_ended
- [ ] Data validation
- [x] Update form
- [x] Update templates

## MembershipOrganization

- [x] MembershipOrganization:realstart
- [x] MembershipOrganziation: realend (seems like maybe this should be open-ended, too?)
- [ ] Data validation
- [x] Update form
- [x] Update templates

#  Violations

- [x] Violation:first_allegation (date)
- [x] Violation:last_update (date)
- [x] Violation:status
- [x] Violation:exact_location
- [ ] Data validation
- [x] Update form
- [x] Update templates

**Comment by jeancochrane** [comment]
@tonysecurityforcemonitor I'm trying to figure out with @evz how the new `Exact Location` attributes should interact with existing [`site` attributes on Emplacements](https://github.com/security-force-monitor/sfm-cms/blob/master/emplacement/models.py#L22) (i.e. Organization Sites). Specifically, `Emplacement.site`s already encode [coordinates](https://github.com/security-force-monitor/sfm-cms/blob/master/geosite/models.py#L18)... given this, would it be simpler for `Exact Location` to be a `Y/N` boolean field? Or is there a case where we might have fuzzy coordinates (expressed by OSM name/ID) as well as exact coordinates, such that there's added value in storing two sets of coordinates for each place?

**Comment by tonysecurityforcemonitor** [comment]
@jeancochrane @evz - thanks for raising this - 

> given this, would it be simpler for Exact Location to be a Y/N boolean field?

the main reason we've included an `Exact Location` in addition to the `Site` is the human readable text associated with the `Exact Location` is usually not meaningful to the user. For instance many times the `Exact Location` will be the name of a building structure such as `Campo Militar Numero 1-A`. That doesn't really indicate to the user where that is - but - if it is `Campo Militar Numero 1-A` with the `Site` of `Mexico City` that's much, much more useful for a user. In the feedback from users having the city and the state/governorate/province/etc. was important for them to get a bearing of where things were.

> Or is there a case where we might have fuzzy coordinates (expressed by OSM name/ID) as well as exact coordinates, such that there's added value in storing two sets of coordinates for each place?

As far as coordinates I guess I was assuming the system would pick the smallest/most exact location - so `Exact Location` if we have it, if not then `Site` and if not that then `admin_1` -rather than two sets of coordinates. I can't think of a reason that we would need two sets of coordinates for the same location. The only thing would be if a unit had two different locations - for example being based in Los Angeles, CA and Chicago, IL at the same time - but then in my mind those are two different locations. Am I answering the question or am I making it more complicated?

**Comment by jeancochrane** [comment]
Hm, maybe I just misunderstand the purpose of what a site si @tonysecurityforcemonitor. Going to check in with @evz and then get back to you.

**Comment by jeancochrane** [comment]
Also, OK by you if I convert your first post to a checkbox? It'll help me keep track of things as I move forward.

**Comment by tonysecurityforcemonitor** [comment]
@jeancochrane - no problem to convert into a checkbox --- also if it's easier to discuss over the phone happy to do so.

**Comment by jeancochrane** [comment]
OK, I think I'm closer to grasping the `Site`/`Exact Location` distinction for units (and the other data types that we're migrating to have an `Exact Location`). Correct me if this is off base: seems like `Exact Location` is an extra level of geographic precision on top of `Site`, in that it's the same sort of data type (point coordinates + OSM Name/ID, where applicable) but at a more fine-grained resolution. So in the same way that the admin levels and country code provide lower-precision context for the `Site`, the `Site` provides context for the higher-precision `Exact Location`. And to answer my question about coordinates, yes, in this data structure we'll wind up having two sets of coordinates (for both `Site` and `Exact Location`), but they're not really the same "type" of coordinates -- where the two attributes exist, it will mean that the `Site` coordinates probably refer to the centroid of a larger area (like `Mexico City` in the example above) and we should prefer the `Exact Location` coordinates; but if we don't have an `Exact Location`, then we can fall back to the lower-precision `Site` coordinates.

Does that sound right to you, @tonysecurityforcemonitor? Sorry for the mouthful (pageful?), but I want to make sure we're on the same page before I write the migration.

**Comment by tonysecurityforcemonitor** [comment]
@jeancochrane - this is exactly right - thanks! And no worries about length it's nothing compared to some of my comments ;)

**Comment by jeancochrane** [comment]
Great! Thanks for clearing that up.

A couple other notes that came up today:

1. It seems like you're using the same `open_ended` logic in `OrganizationMembership:end_date` and `AreaOfOperation:assume_to_current_date`, just with different names. Do you mind if I use `open_ended` (with the accompanying `Y/N/E` choices) under the hood for those two types, as well?

2. I like the idea of aliases for HQs. Seems pretty straightforward to implement as an attribute on `Emplacements`. Should I go ahead with it? We can leave them as `NULLs` for now; will just help avoid future migrations if you decide you want to move forward.

3. Personnel attributes should be no problem to add on later, as long as it's static data like `age` and `gender` and not foreign-key relationships to other entities in the DB.

Thanks for the speedy replies today @tonysecurityforcemonitor, it's been immensely helpful!

**Comment by tonysecurityforcemonitor** [comment]
@jeancochrane - all of those three points sounds good, no issues on this side. Thank you @jeancochrane @reginafcompton and @evz for all of your speedy work today!
